# Practice with Data Structures in Python

## Sheikh Irfan Ullah Khan

### Contact Me: shirfan.math@gmail.com

### 1. Create a Series objects using numpy linspace and random module

In [1]:
# Import the required libraries
import pandas as pd
import numpy as np

In [2]:
# Use linspace to create a series of numbers
x = np.linspace(0, 10)
x[:20]

array([0.        , 0.20408163, 0.40816327, 0.6122449 , 0.81632653,
       1.02040816, 1.2244898 , 1.42857143, 1.63265306, 1.83673469,
       2.04081633, 2.24489796, 2.44897959, 2.65306122, 2.85714286,
       3.06122449, 3.26530612, 3.46938776, 3.67346939, 3.87755102])

In [3]:
# Use the above sample data to create a series
s = pd.Series(x)
s.head()

0    0.000000
1    0.204082
2    0.408163
3    0.612245
4    0.816327
dtype: float64

In [4]:
# Create a series using linspace with n = 5
y = np.linspace(0, 10, 5)
y

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [5]:
s1 = pd.Series(y)
s1

0     0.0
1     2.5
2     5.0
3     7.5
4    10.0
dtype: float64

In [6]:
# Generate array of random numbers
z = np.random.rand(10)
z

array([0.0244621 , 0.44222557, 0.72417803, 0.06538082, 0.96797987,
       0.34655619, 0.86343742, 0.93319835, 0.29086095, 0.17681019])

In [7]:
s2 = pd.Series(z)
s2

0    0.024462
1    0.442226
2    0.724178
3    0.065381
4    0.967980
5    0.346556
6    0.863437
7    0.933198
8    0.290861
9    0.176810
dtype: float64

### 2. Create a Series using a list of elements

In [8]:
list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
s3 = pd.Series(list)
s3

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

### 3. For the given data, find the index and values after forming a series

In [9]:
# Generate a random data of 5 countries with their capitals using dictionary
d = {'Pakistan': 'Islamabad', 'USA': 'Washington DC', 'China': 'Beijing', 'Japan': 'Tokyo', 'Germany': 'Berlin'}
s4 = pd.Series(d)
s4

Pakistan        Islamabad
USA         Washington DC
China             Beijing
Japan               Tokyo
Germany            Berlin
dtype: object

In [10]:
s4.index

Index(['Pakistan', 'USA', 'China', 'Japan', 'Germany'], dtype='object')

In [11]:
s4.values

array(['Islamabad', 'Washington DC', 'Beijing', 'Tokyo', 'Berlin'],
      dtype=object)

### 4. Create a Series using a range of 15 values ans specify the index explicitly.

In [12]:
# Use capaital alphabet to index explicitly
e = np.arange(15)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
# Create an index list using capital alphabet starting from A
ind_values = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O']
s5 = pd.Series(e, index=ind_values)
s5



A     0
B     1
C     2
D     3
E     4
F     5
G     6
H     7
I     8
J     9
K    10
L    11
M    12
N    13
O    14
dtype: int32